### ISSUE TITLE
fcs threshold

### ISSUE THREAD

**Issue by yannsay-impact** [SaeedR1987/healthyr#2]
It seems the threshold for the fcs are .5 point off. 28 should be included in poor rather than borderline. 

![image](https://user-images.githubusercontent.com/79831444/168292460-300e16a5-2b14-47b3-8cc5-d40a167ec950.png)

**Comment by SaeedR1987** [comment]
Updating in next commit #9 so elevated FCS thresholds count 28.0 as Poor, as discussed.
